### ISSUE TITLE
上传超大文件一直转圈

### ISSUE THREAD

**Issue by Adoirsa** [PeterDing/AliPCS-Py#4]
上传 100G 的文件，一直在转圈，转了半个小时了。是在切片吗

**Comment by PeterDing** [comment]
应该是在算快速上传用的文件sha1。这个方法对大文件可能会很慢。等我优化一下。

**Comment by Adoirsa** [comment]
> 应该是在算快速上传用的文件sha1。这个方法对大文件可能会很慢。等我优化一下。

我觉得可以加个选项控制要不要检测快速上传

**Comment by PeterDing** [comment]
可以

**Comment by Adoirsa** [comment]
[日志.txt](https://github.com/PeterDing/AliPCS-Py/files/10301629/default.txt)
好像不是在算sha1，我这边开了日志之后又试了一下 一直报错。文件大于100G就会报错，我用小于100G的文件测试就正常

**Comment by PeterDing** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/670690/209506012-5e0d5dfb-1a7b-44a7-9387-8146687d773a.png">

非会员用户最多只能上传 100G 大小的文件。

**Comment by Adoirsa** [comment]
我是傻逼

**Comment by Adoirsa** [comment]
不对啊，我冲了会员之后还是相同的报错，用网页端测试相同文件可以上传

**Comment by PeterDing** [comment]
把 AliPCS-Py 的用户先删除，再添加试试

**Comment by Adoirsa** [comment]
试过了

**Comment by PeterDing** [comment]
等我复现看看。

**Comment by Adoirsa** [comment]
好的

**Comment by PeterDing** [comment]
@Adoirsa 已经在 v0.4.0 修复。
